In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
s1=pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [3]:
s2=pd.Series([-2.1,3.6,-3.4,3.1,4], index=['a','c','e','f','g'])

In [4]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2

a   -2.1
c    3.6
e   -3.4
f    3.1
g    4.0
dtype: float64

In [6]:
s1+s2

a    5.2
c    1.1
d    NaN
e   -1.9
f    NaN
g    NaN
dtype: float64

In [26]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                 index=['A','B','C'])

In [27]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                 index=['F','A','B','D'])

In [10]:
df1

b    c    d
A  0.0  1.0  2.0
B  3.0  4.0  5.0
C  6.0  7.0  8.0

In [11]:
df2

b     d     e
F  0.0   1.0   2.0
A  3.0   4.0   5.0
B  6.0   7.0   8.0
D  9.0  10.0  11.0

In [12]:
df1+df2

b   c     d   e
A  3.0 NaN   6.0 NaN
B  9.0 NaN  12.0 NaN
C  NaN NaN   NaN NaN
D  NaN NaN   NaN NaN
F  NaN NaN   NaN NaN

In [17]:
df1=pd.DataFrame({'a': [1,2]})

In [18]:
df2=pd.DataFrame({'b': [3,4]})

In [19]:
df1

a
0  1
1  2

In [20]:
df2

b
0  3
1  4

In [21]:
df1-df2

a   b
0 NaN NaN
1 NaN NaN

In [28]:
df1.add(df2, fill_value=0)

b    c     d     e
A  3.0  1.0   6.0   5.0
B  9.0  4.0  12.0   8.0
C  6.0  7.0   8.0   NaN
D  9.0  NaN  10.0  11.0
F  0.0  NaN   1.0   2.0

In [29]:
1/df1

b         c      d
A       inf  1.000000  0.500
B  0.333333  0.250000  0.200
C  0.166667  0.142857  0.125

In [30]:
df1.rdiv(1)

b         c      d
A       inf  1.000000  0.500
B  0.333333  0.250000  0.200
C  0.166667  0.142857  0.125

In [31]:
arr=np.arange(12.).reshape((3,4))

In [32]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
arr[0]

array([0., 1., 2., 3.])

In [34]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['A','B','C','D'])

In [35]:
series=frame.iloc[0]

In [36]:
frame

b     d     e
A  0.0   1.0   2.0
B  3.0   4.0   5.0
C  6.0   7.0   8.0
D  9.0  10.0  11.0

In [37]:
series

b    0.0
d    1.0
e    2.0
Name: A, dtype: float64

In [38]:
frame=pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                  index=['A','B','C','D'])

In [39]:
frame

b         d         e
A -0.563128  0.662493 -1.398726
B -0.028562 -0.031491 -0.819725
C  0.329402 -0.579145 -1.410693
D  0.357783 -0.669885  0.233272

In [40]:
np.abs(frame)

b         d         e
A  0.563128  0.662493  1.398726
B  0.028562  0.031491  0.819725
C  0.329402  0.579145  1.410693
D  0.357783  0.669885  0.233272

In [41]:
f=lambda x:x.max()-x.min()

In [42]:
frame.apply(f)

b    0.920911
d    1.332378
e    1.643965
dtype: float64

In [43]:
frame.apply(f,axis='columns')

A    2.061220
B    0.791163
C    1.740095
D    1.027668
dtype: float64

In [44]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [45]:
frame.apply(f)

b         d         e
min -0.563128 -0.669885 -1.410693
max  0.357783  0.662493  0.233272

In [46]:
format=lambda x:'%.2f' %x

In [47]:
frame.applymap(format)

b      d      e
A  -0.56   0.66  -1.40
B  -0.03  -0.03  -0.82
C   0.33  -0.58  -1.41
D   0.36  -0.67   0.23

In [48]:
frame['e'].map(format)

A    -1.40
B    -0.82
C    -1.41
D     0.23
Name: e, dtype: object

In [49]:
obj=pd.Series(range(4),index=['d','a','b','c'])

In [50]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [52]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                  index=['three','one'],
                  columns=['d','a','b','c'])

In [53]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [54]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [55]:
obj=pd.Series([4,7,-3,2])

In [56]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [57]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [58]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [59]:
frame=pd.DataFrame({'b': [4,7,-3,2],'a':[0,1,0,1]})

In [60]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [61]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [62]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [63]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [64]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [65]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [66]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [69]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [70]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [71]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [72]:
obj=pd.Series(range(5), index=['a','a','b','b','c'])

In [73]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [74]:
obj.index.is_unique

False

In [75]:
obj['a']

a    0
a    1
dtype: int64

In [76]:
obj['c']

4

In [77]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [78]:
df

0         1         2
a  0.324903 -0.077536 -0.457526
a -1.442076  1.105757  0.993294
b -0.272115 -0.982835  1.641753
b -0.065774  0.403954 -0.154097

In [79]:
df.loc['b']

0         1         2
b -0.272115 -0.982835  1.641753
b -0.065774  0.403954 -0.154097

In [80]:
df=pd.DataFrame([[1.4,np.nan], [7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
               index=['a','b','c','d'],
               columns=['one','two'])

In [81]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [82]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [84]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [85]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [87]:
df.idxmax()

one    b
two    d
dtype: object

In [88]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [89]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [93]:
obj=pd.Series(['a','a','b','c','d']*4)

In [94]:
obj

0     a
1     a
2     b
3     c
4     d
5     a
6     a
7     b
8     c
9     d
10    a
11    a
12    b
13    c
14    d
15    a
16    a
17    b
18    c
19    d
dtype: object

In [95]:
obj.describe()

count     20
unique     4
top        a
freq       8
dtype: object

In [96]:
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Cie\anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.1               |   py38haa95532_1         2.9 MB
    pandas-datareader-0.9.0    |             py_0          72 KB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.9.0-py_0

The following packages will be UPDATED:

  conda                                4.9.2-py38haa95532_0 --> 4.10.1-py38haa95532_1




conda-4.10.1         | 2.9 MB    |            |   0% 
conda-4.10.1         | 2.9 MB    | 1          |   2% 
conda-4.10.1         | 2.9 MB    | ########8  |  88% 
conda-4.10.1         | 2.9

In [97]:
import pandas_datareader.data as web
all_data = {ticker : web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker : data['Adj Close']
                   for ticker, data in all_data.items()})
volume=pd.DataFrame({ticker : data['Volume']
                   for ticker, data in all_data.items()})

In [98]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2016-05-16   21.925322  119.672348   47.526649   716.489990
2016-05-17   21.834238  118.503326   46.640190   706.229980
2016-05-18   22.084131  117.974838   46.917206   706.630005
2016-05-19   22.000053  116.045166   46.464745   700.320007
2016-05-20   22.238272  117.902802   46.741768   709.739990
...                ...         ...         ...          ...
2021-05-10  126.849998  146.169998  247.179993  2341.659912
2021-05-11  125.910004  144.220001  246.229996  2308.760010
2021-05-12  122.769997  141.300003  239.000000  2239.080078
2021-05-13  124.970001  144.169998  243.029999  2261.969971
2021-05-14  127.449997  144.679993  248.149994  2316.159912

[1259 rows x 4 columns]

In [99]:
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2016-05-16  245039200.0  3069100.0  20032000.0  1317100
2016-05-17  187667600.0  3490600.0  27803500.0  2001200
2016-05-18  168249600.0  2491100.0  24907500.0  1766800
2016-05-19  121768400.0  3685600.0  23842400.0  1670200
2016-05-20  128104000.0  3671500.0  23905800.0  1828400
...                 ...        ...         ...      ...
2021-05-10   88071200.0  6983400.0  29299900.0  1300300
2021-05-11  126142800.0  7126400.0  33641600.0  1605500
2021-05-12  112172300.0  5959600.0  36684400.0  1746700
2021-05-13  105861300.0  4595800.0  29624300.0  1333500
2021-05-14   81806500.0  2746900.0  23868600.0  1330100

[1259 rows x 4 columns]

In [100]:
returns = price.pct_change()

In [101]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-05-10 -0.025805  0.004881 -0.020914 -0.023775
2021-05-11 -0.007410 -0.013341 -0.003843 -0.014050
2021-05-12 -0.024939 -0.020247 -0.029363 -0.030181
2021-05-13  0.017920  0.020311  0.016862  0.010223
2021-05-14  0.019845  0.003537  0.021067  0.023957

In [102]:
returns['MSFT'].corr(returns['IBM'])

0.5315103149997493

In [103]:
returns['MSFT'].cov(returns['IBM'])

0.0001509338174729594

In [104]:
print(returns.MSFT.corr(returns.IBM))
print(returns.MSFT.cov(returns.IBM))

0.5315103149997493
0.0001509338174729594


In [105]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.447369  0.724753  0.659497
IBM   0.447369  1.000000  0.531510  0.494430
MSFT  0.724753  0.531510  1.000000  0.771940
GOOG  0.659497  0.494430  0.771940  1.000000

In [106]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000363  0.000140  0.000239  0.000212
IBM   0.000140  0.000269  0.000151  0.000137
MSFT  0.000239  0.000151  0.000300  0.000225
GOOG  0.000212  0.000137  0.000225  0.000283

In [107]:
returns.corrwith(returns.IBM)

AAPL    0.447369
IBM     1.000000
MSFT    0.531510
GOOG    0.494430
dtype: float64

In [108]:
returns.corrwith(volume)

AAPL   -0.054503
IBM    -0.099765
MSFT   -0.062422
GOOG   -0.114794
dtype: float64

In [109]:
returns.corrwith(volume,axis=1)

Date
2016-05-16         NaN
2016-05-17    0.740397
2016-05-18    0.849632
2016-05-19    0.788237
2016-05-20   -0.269548
                ...   
2021-05-10   -0.481592
2021-05-11    0.527156
2021-05-12    0.072953
2021-05-13    0.308166
2021-05-14    0.279546
Length: 1259, dtype: float64

In [110]:
obj=pd.Series(['c','a','d','a','b','b','c','c'])

In [111]:
mask=obj.isin(['b','c'])

In [112]:
mask

0     True
1    False
2    False
3    False
4     True
5     True
6     True
7     True
dtype: bool

In [113]:
obj[mask]

0    c
4    b
5    b
6    c
7    c
dtype: object

In [114]:
to_match=pd.Series(['c','a','b','b','c','a'])

In [115]:
unique_vals=pd.Series(['c','b','a'])

In [117]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [118]:
data=pd.DataFrame({'Qu1': [1,3,4,3,4],
                  'Qu2': [2,3,1,2,3],
                  'Qu3': [1,5,2,4,4,]})

In [119]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [120]:
result=data.apply(pd.value_counts).fillna(0)

In [121]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0