In [1]:
import numpy as np
import pandas as pd

In [2]:
values = pd.Series(['apple','orange','apple','apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [3]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [4]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [5]:
values=pd.Series([0, 1, 0, 0] * 2)
dim=pd.Series(['apple','orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [6]:
dim

0     apple
1    orange
dtype: object

In [7]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [8]:
np.random.seed(12345)
draws=np.random.randn(1000)
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [9]:
bins=pd.qcut(draws, 4)
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [10]:
bins=pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [11]:
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [13]:
bins=pd.Series(bins, name='quartile')

In [26]:
results=(pd.Series(draws)
           .groupby(bins)
           .agg(['count','min','max'])
           .reset_index())
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [27]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                   'value': np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [28]:
g=df.groupby('key').value
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [29]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [65]:
g.transform(lambda x: x.rank(ascending=True))

0     1.0
1     1.0
2     1.0
3     2.0
4     2.0
5     2.0
6     3.0
7     3.0
8     3.0
9     4.0
10    4.0
11    4.0
Name: value, dtype: float64

In [66]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [67]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [33]:
N=15
times=pd.date_range('2017-05-20 00:00', freq='1min', periods=N)

In [68]:
df=pd.DataFrame({'time': times,
                   'value': np.arange(N)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [69]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [115]:
df2=pd.DataFrame({'time': times.repeat(3),
                    'key': np.tile(['a', 'b', 'c'], N),
                    'value': np.arange(N * 3.)})
df2[:7]

time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [117]:
time_key=pd.Grouper('5min')

In [119]:
resampled=(df2.set_index('time')
             .groupby(['key',time_key])
             .sum())

KeyError: 'The grouper name 5min is not found'

In [120]:
import pandas as pd
import numpy as np

In [121]:
data=pd.DataFrame({
    'x0': [1,2,3,4,5],
    'x1': [0.01,-0.01,0.25,-4.1,0], 
    'y': [-1.5,0.,3.6,1.3,-2.]})
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [122]:
df2=pd.DataFrame(data.values,columns=['one','two','three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [125]:
df4 = data.copy()
df4['그냥해보기']=['1','2','3','4','5']
df4

x0    x1    y 그냥해보기
0   1  0.01 -1.5     1
1   2 -0.01  0.0     2
2   3  0.25  3.6     3
3   4 -4.10  1.3     4
4   5  0.00 -2.0     5

In [126]:
model_cols=['x0','x1']
data.loc[:,model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [127]:
import patsy
y,X=patsy.dmatrices('y ~ x0 + x1',data)
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [128]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [129]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [130]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [131]:
patsy.dmatrices('y ~ x0 + x1 + 0',data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [132]:
y,X=patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) +1)',data)
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [133]:
y,X=patsy.dmatrices('y ~ standardize(x0) + center(x1)',data)
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [134]:
new_data=pd.DataFrame({
    'x0': [6,7,8,9],
    'x1': [3.1,-0.5,0,2.3],
    'y' : [1,2,3,4]})

In [135]:
new_X=patsy.build_design_matrices([X.design_info],new_data)

In [136]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [137]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [138]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [139]:
np.random.seed(12345)

In [156]:
N=100
X=np.c_[dnorm(0, 0.4, size=N),
         dnorm(0, 0.6, size=N),
         dnorm(0, 0.2, size=N)]
eps=dnorm(0, 0.1, size=N)
beta=[0.1, 0.3, 0.5]

In [157]:
y=np.dot(X,beta)+eps

In [158]:
X[:5]

array([[ 0.53954036, -0.72936504,  0.71113599],
       [ 0.24779043,  1.12355877, -0.36689848],
       [-1.87891273,  0.56144232, -0.43450393],
       [ 0.44209991,  0.17309593, -0.17748382],
       [ 0.17697673,  0.49278756,  0.95798115]])

In [159]:
y[:5]

array([0.38116746, 0.28671775, 0.38160007, 0.06285077, 0.35700376])

In [160]:
X_model=sm.add_constant(X)
X_model[:5]

array([[ 1.        ,  0.53954036, -0.72936504,  0.71113599],
       [ 1.        ,  0.24779043,  1.12355877, -0.36689848],
       [ 1.        , -1.87891273,  0.56144232, -0.43450393],
       [ 1.        ,  0.44209991,  0.17309593, -0.17748382],
       [ 1.        ,  0.17697673,  0.49278756,  0.95798115]])

In [161]:
model=sm.OLS(y,X)

In [162]:
results=model.fit()
results.params

array([0.06592248, 0.3068162 , 0.44247497])

In [163]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.464
Model:                            OLS   Adj. R-squared (uncentered):              0.447
Method:                 Least Squares   F-statistic:                              27.97
Date:                Sun, 04 Jul 2021   Prob (F-statistic):                    4.07e-13
Time:                        11:41:50   Log-Likelihood:                         -24.883
No. Observations:                 100   AIC:                                      55.77
Df Residuals:                      97   BIC:                                      63.58
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [164]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [165]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [173]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [184]:
impute_value=train['Age'].median()

In [185]:
train['Age']=train['Age'].fillna(impute_value)
test['Age']=test['Age'].fillna(impute_value)

In [186]:
train['IsFemale']=(train['Sex']=='female').astype(int)
test['IsFemale']=(test['Sex']=='female').astype(int)

In [188]:
predictors=['Pclass','IsFemale','Age']
X_train=train[predictors].values
X_test=test[predictors].values
y_train=train['Survived'].values

In [189]:
from sklearn.linear_model import LogisticRegression          
model=LogisticRegression()

In [190]:
model.fit(X_train, y_train)

LogisticRegression()

In [192]:
y_predict=model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [193]:
from sklearn.model_selection import cross_val_score

In [194]:
model=LogisticRegression(C=10)

In [197]:
scores=cross_val_score(model,X_train,y_train,cv=4)

In [198]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])